hash-format = "sha256"

[[files]]
file = "config/c2me.toml"
hash = "5d0a7606977a8f774e1024f466a9181aa1a3b30a291761a4f90eeebf0ce81335"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "c5617a8aeeed635b36e4b6311ef6d89bfd464c67d4d7e8fe07f9df1e385aff02"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3cc3011619f098fda6ad213a7c4d1468802ff827591a5917c2b7bf3150bfb2ea"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/spark/tmp/about.txt"
hash = "8057ccf4540ea269b0fc332225859f44d8f3a55d891fa2e7a3447b6202658d2a"

[[files]]
file = "mods/c2me.pw.toml"
hash = "9450f8a2ef35fe0265d092e6b56738303c6f5f70f3014a648324ddb67a84b61e"
metafile = true

[[files]]
file = "mods/cardboard.pw.toml"
hash = "c6b6ec6e13acdf2f716c9a3b2acd5b33e2c42742912696b20c2ef589763446f9"
metafile = true

[[files]]
file = "mods/chunky-pregenerator.pw.toml"
hash = "c68f944fcd86db1d7d8da124d838fdcd1367147f7c43db33e8f5e0f2211fa7a5"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "6a9e19fada33c165b2aafa879179fb45de0eeb039bb0f4e9ca6bdb678441a656"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "638ada423b2201d0157dcb7f039f49728b193f9e573d30c9970c2a0f16fb1380"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e1abc1f3938e26029a550172b3e616c8e62f14a4988aefe0c2d9c768298c8fca"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "b06945aaa6a338deed3db1240c33cea24655fe687f0618be9d4ba4bfe0863f7a"
metafile = true
