hash-format = "sha256"

[[files]]
file = "config/c2me.toml"
hash = "5d0a7606977a8f774e1024f466a9181aa1a3b30a291761a4f90eeebf0ce81335"

[[files]]
file = "config/fabric/indigo-renderer.properties"
hash = "c5617a8aeeed635b36e4b6311ef6d89bfd464c67d4d7e8fe07f9df1e385aff02"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "3cc3011619f098fda6ad213a7c4d1468802ff827591a5917c2b7bf3150bfb2ea"

[[files]]
file = "config/lithium.properties"
hash = "6cf6f83720071fd1657c8e79b357caf68d40f410ae123e5f922483eb1d1d25be"

[[files]]
file = "config/spark/tmp/about.txt"
hash = "8057ccf4540ea269b0fc332225859f44d8f3a55d891fa2e7a3447b6202658d2a"

[[files]]
file = "mods/c2me.pw.toml"
hash = "86a83e2ffeda465136d95765222d5498a62d4e7d5d7a43ac1a9e06180bf4c971"
metafile = true

[[files]]
file = "mods/cardboard.pw.toml"
hash = "a1ec3a83ca0aa8e3e407809a5293cf415dac9c5bdda2b5869fa0c940d4ecbd25"
metafile = true

[[files]]
file = "mods/chunky-pregenerator.pw.toml"
hash = "a43dec6f1aad05518a1ac1056a53cdfa357d1a46e19ffb945632e7fd0fb02644"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1943cee706f90e5e828de013387ee1d1ae9ec1ae6a63da767be9bfd64018b79a"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "e3d00ba5bb65702b984da8ee63dd6f87a1d0c2b818d0fb1d21e4197a591db73b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "6fd385ab7c8e30ff3fb79a941e5149b16e0a971e6feddbd5902f3cfc5e9aba4d"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "9d1a394fcc096e7b11b34e631f2fd758d2184a5f51e4daa5761c427b074bf8f8"
metafile = true
