name = "yes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19bf74e1b41f3021f244d1ef7ad31f04e1454ac9427db05c3df8345c65ccebc3"

[versions]
fabric = "0.17.0"
minecraft = "1.21.8"
