name = "yes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7685ce1581c0dde49e12779b931a32f4073ced8bfb7aca0b36c3a81ac2b348e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
